# Generated by Django 5.2.8 on 2025-11-28 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twitter', '0002_tweet_author_display_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('num_tweets_fetched', models.IntegerField(default=0)),
                ('num_categories', models.IntegerField(default=0)),
                ('config_num_tweets', models.IntegerField(default=100, help_text='Configured number of tweets to fetch')),
                ('twitter_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curated_feeds', to='twitter.twitterprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curated_feeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TweetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary of tweets in this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curated_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='bookmarks_app.curatedfeed')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('curated_feed', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CategorizedTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorized_in', to='twitter.tweet')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='bookmarks_app.tweetcategory')),
            ],
            options={
                'ordering': ['-tweet__created_at'],
                'unique_together': {('category', 'tweet')},
            },
        ),
    ]
