# Generated by Django 5.2.8 on 2025-12-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks_app', '0003_backfill_curatedfeed_processing_date'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='curatedfeed',
            new_name='bookmarks_a_process_8489cd_idx',
            old_name='bookmarks_a_processing_date_idx',
        ),
    ]
