# Generated by Django 5.2.8 on 2025-11-28 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twitter', '0002_tweet_author_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('list_name', models.CharField(max_length=200)),
                ('list_slug', models.CharField(blank=True, max_length=200)),
                ('list_url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('member_count', models.IntegerField(default=0)),
                ('subscriber_count', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('twitter_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_lists', to='twitter.twitterprofile')),
            ],
            options={
                'ordering': ['list_name'],
                'unique_together': {('twitter_profile', 'list_id')},
            },
        ),
        migrations.CreateModel(
            name='ListTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_tweets', to='twitter.tweet')),
                ('twitter_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='lists_app.twitterlist')),
            ],
            options={
                'ordering': ['-seen_date', '-tweet__created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(db_index=True)),
                ('headline', models.CharField(help_text='Generated headline for the event', max_length=500)),
                ('summary', models.TextField(help_text='AI-generated summary of the event from all related tweets')),
                ('tweet_count', models.IntegerField(default=0, help_text='Number of tweets in this event')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='Keywords that identify this event')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('twitter_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='lists_app.twitterlist')),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tweets', to='lists_app.event')),
                ('list_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='lists_app.listtweet')),
            ],
            options={
                'ordering': ['-relevance_score', '-list_tweet__tweet__created_at'],
                'unique_together': {('event', 'list_tweet')},
            },
        ),
        migrations.AddIndex(
            model_name='listtweet',
            index=models.Index(fields=['twitter_list', 'seen_date'], name='lists_app_l_twitter_b84c66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listtweet',
            unique_together={('twitter_list', 'tweet', 'seen_date')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['twitter_list', 'event_date'], name='lists_app_e_twitter_29dece_idx'),
        ),
    ]
