# Generated by Django 5.2.8 on 2025-12-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentprocessingjob',
            new_name='processing__user_id_3f2bee_idx',
            old_name='processing__user_id_processing_date_content_type_idx',
        ),
        migrations.RenameIndex(
            model_name='contentprocessingjob',
            new_name='processing__status_571a5b_idx',
            old_name='processing__status_next_retry_at_idx',
        ),
        migrations.RenameIndex(
            model_name='contentprocessingjob',
            new_name='processing__twitter_fcf132_idx',
            old_name='processing__twitter_profile_content_type_processing_date_idx',
        ),
        migrations.RenameIndex(
            model_name='dailycontentsnapshot',
            new_name='processing__user_id_283c37_idx',
            old_name='processing__user_id_processing_date_idx',
        ),
        migrations.RenameIndex(
            model_name='dailycontentsnapshot',
            new_name='processing__twitter_6622fd_idx',
            old_name='processing__twitter_profile_processing_date_idx',
        ),
    ]
