# Generated by Django 5.2.8 on 2025-11-27 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('author_username', models.CharField(max_length=100)),
                ('author_id', models.CharField(blank=True, max_length=100)),
                ('text_content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('like_count', models.IntegerField(default=0)),
                ('retweet_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('is_bookmark', models.BooleanField(default=True)),
                ('is_reply', models.BooleanField(default=False)),
                ('in_reply_to_tweet_id', models.CharField(blank=True, max_length=100, null=True)),
                ('conversation_id', models.CharField(blank=True, max_length=100)),
                ('thread_position', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TweetMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('gif', 'GIF')], max_length=10)),
                ('file_path', models.CharField(max_length=500)),
                ('original_url', models.URLField(max_length=1000)),
                ('thumbnail_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='twitter.tweet')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwitterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_username', models.CharField(max_length=100)),
                ('twitter_user_id', models.CharField(blank=True, max_length=100)),
                ('encrypted_credentials', models.TextField(help_text='Encrypted Twitter credentials')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('sync_error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='twitter_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='twitter.twitterprofile'),
        ),
        migrations.CreateModel(
            name='TweetReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_author_username', models.CharField(max_length=100)),
                ('reply_author_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='twitter.tweet')),
                ('reply_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_to', to='twitter.tweet')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('original_tweet', 'reply_tweet')},
            },
        ),
        migrations.CreateModel(
            name='TweetThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_threads', to='twitter.tweet')),
                ('parent_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_threads', to='twitter.tweet')),
            ],
            options={
                'ordering': ['thread_order'],
                'unique_together': {('parent_tweet', 'child_tweet')},
            },
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['tweet_id'], name='twitter_twe_tweet_i_8aba88_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['conversation_id'], name='twitter_twe_convers_5bb875_idx'),
        ),
        migrations.AddIndex(
            model_name='tweet',
            index=models.Index(fields=['-created_at'], name='twitter_twe_created_3042dd_idx'),
        ),
    ]
