# Generated by Django 5.2.8 on 2025-11-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='author_display_name',
            field=models.CharField(blank=True, help_text="Display name (e.g., 'Dave Shapiro')", max_length=200),
        ),
        migrations.AddField(
            model_name='tweet',
            name='author_profile_image_url',
            field=models.URLField(blank=True, help_text='Profile picture URL', max_length=500),
        ),
        migrations.AddField(
            model_name='tweet',
            name='html_content',
            field=models.TextField(blank=True, help_text='Original HTML from x.com'),
        ),
        migrations.AddField(
            model_name='tweet',
            name='html_content_sanitized',
            field=models.TextField(blank=True, help_text='Sanitized HTML with local URLs and no JavaScript'),
        ),
    ]
