# Generated by Django 5.2.8 on 2025-12-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_backfill_tweet_processing_date'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tweet',
            new_name='twitter_twe_process_cd767c_idx',
            old_name='twitter_twe_processing_date_idx',
        ),
    ]
