# Generated by Django 5.2.10 on 2026-03-03 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_rename_twitter_twe_processing_date_idx_twitter_twe_process_cd767c_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkSyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('interval_minutes', models.IntegerField(default=60, help_text='Base interval between syncs (minutes)')),
                ('randomize_minutes', models.IntegerField(default=15, help_text='Random variation to add (±minutes)')),
                ('timezone', models.CharField(default='Europe/Copenhagen', max_length=50)),
                ('start_hour', models.IntegerField(default=8, help_text='Start hour (0-23)')),
                ('end_hour', models.IntegerField(default=24, help_text='End hour (0-23)')),
                ('max_pages', models.IntegerField(default=2, help_text='Pages to fetch (~40 bookmarks per page)')),
                ('use_until_synced', models.BooleanField(default=False, help_text='Use gap-free sync mode (rebuild)')),
                ('last_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('next_sync_at', models.DateTimeField(blank=True, null=True)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('twitter_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_schedule', to='twitter.twitterprofile')),
            ],
            options={
                'verbose_name': 'Bookmark Sync Schedule',
                'verbose_name_plural': 'Bookmark Sync Schedules',
            },
        ),
        migrations.CreateModel(
            name='BookmarkSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('bookmarks_fetched', models.IntegerField(default=0)),
                ('pages_fetched', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('error_type', models.CharField(blank=True, help_text="e.g., 'cookie_expired', 'rate_limit', 'network_error'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('twitter_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='twitter.twitterprofile')),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['twitter_profile', '-scheduled_at'], name='twitter_boo_twitter_9b19e2_idx'), models.Index(fields=['status', 'scheduled_at'], name='twitter_boo_status_627ab6_idx')],
            },
        ),
    ]
