# Generated by Django 5.2.10 on 2026-08-02 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_bookmarksyncschedule_backoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarksyncschedule',
            name='fetch_margin_pages',
            field=models.IntegerField(default=2, help_text='Extra pages fetched beyond the watermark, covering bookmarks added since the last run'),
        ),
        migrations.AddField(
            model_name='bookmarksyncschedule',
            name='full_rebuild_interval_days',
            field=models.IntegerField(default=7, help_text='Force an unbounded walk this often (0 = never). Catches bookmarks a bounded fetch cannot see.'),
        ),
        migrations.AddField(
            model_name='bookmarksyncschedule',
            name='last_full_rebuild_at',
            field=models.DateTimeField(blank=True, help_text='Last unbounded walk of the whole bookmark list', null=True),
        ),
        migrations.AddField(
            model_name='bookmarksyncschedule',
            name='verification_ignored_ids',
            field=models.JSONField(blank=True, default=list, help_text='Tweet IDs quarantined from the watermark: gaps no re-fetch can repair (e.g. deleted tweets). Without this one dead record pins the watermark forever.'),
        ),
        migrations.AddField(
            model_name='bookmarksyncschedule',
            name='verification_report',
            field=models.JSONField(blank=True, default=dict, help_text='Last verification result (gaps, counts, timings)'),
        ),
        migrations.AddField(
            model_name='bookmarksyncschedule',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the verification pass last ran', null=True),
        ),
        migrations.AddField(
            model_name='bookmarksyncschedule',
            name='verified_count',
            field=models.IntegerField(default=0, help_text='Bookmarks covered by the watermark at the last verification'),
        ),
        migrations.AddField(
            model_name='bookmarksyncschedule',
            name='verified_ok_before',
            field=models.DateTimeField(blank=True, help_text='All bookmarks ingested at or before this time are verified complete', null=True),
        ),
        migrations.AlterField(
            model_name='bookmarksyncschedule',
            name='end_hour',
            field=models.IntegerField(default=24, help_text='End hour (1-24, where 24 = end of day)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='bookmarksyncschedule',
            name='start_hour',
            field=models.IntegerField(default=8, help_text='Start hour (0-23)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
    ]
