# Generated by Django 5.2.8 on 2025-11-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic Claude'), ('openai', 'OpenAI')], default='anthropic', help_text='AI provider to use for categorization and summarization', max_length=20),
        ),
    ]
